#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <signal.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/file.h>
#include <netinet/ip.h>
#include <arpa/ftp.h>
#include <netdb.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdio.h>
#include <errno.h>
#include <syslog.h>
#include <string.h>
#include <setjmp.h>
#include <unistd.h>
#include <string.h>
#include <dirent.h>
#define  MAXLINE 1024
